// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetUpForDebug
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSetUpForDebugPackageString = "5a77b1be-9f79-44cc-9404-e468816ba1a8";
        public static Guid guidSetUpForDebugPackage = new Guid(guidSetUpForDebugPackageString);

        public const string guidSetUpForDebugPackageCmdSetString = "f40b03a5-f476-4645-93b1-10d3b0493b37";
        public static Guid guidSetUpForDebugPackageCmdSet = new Guid(guidSetUpForDebugPackageCmdSetString);

        public const string guidImagesString = "3c8a51e8-db7b-48de-b2b0-fc990b598a01";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}